const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store, max-age=0","x-content-type-options":"nosniff"};
function json(data,status=200,extraHeaders={}){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extraHeaders}})}
function text(value,maxLength=5000){return String(value??"").trim().slice(0,maxLength)}
function tokenFrom(request){const authorization=request.headers.get("Authorization")||"";const bearer=authorization.match(/^Bearer\s+(.+)$/i);return text(bearer?.[1]||request.headers.get("X-Admin-Token"),500)}
function constantTimeEqual(a,b){const left=new TextEncoder().encode(String(a||""));const right=new TextEncoder().encode(String(b||""));const length=Math.max(left.length,right.length);let diff=left.length^right.length;for(let i=0;i<length;i++)diff|=(left[i]||0)^(right[i]||0);return diff===0}
function requireAdmin(request,env){if(!env.ADMIN_TOKEN)return json({ok:false,message:"Chưa cấu hình ADMIN_TOKEN trên Cloudflare."},503);const supplied=tokenFrom(request);if(!supplied||!constantTimeEqual(supplied,env.ADMIN_TOKEN))return json({ok:false,message:"Mật khẩu quản trị không đúng."},401,{"www-authenticate":'Bearer realm="TrainingBot Admin"'});return null}
async function readJson(request){const ct=request.headers.get("Content-Type")||"";if(!ct.toLowerCase().includes("application/json"))throw new Error("Dữ liệu gửi lên phải có định dạng JSON.");return request.json()}
function normalizeContentPage(value){let page=text(value,300).split("?")[0].split("#")[0];if(!page||page==="/")return "/index.html";if(!page.startsWith("/"))page=`/${page}`;if(page.endsWith("/"))page+="index.html";if(page.includes("..")||!/^\/[a-zA-Z0-9_./-]+$/.test(page))return "";return page}
const CONTENT_FIELDS=new Set(["text","html","src","href","alt","title","style","hidden","placeholder","value"]);
function normalizeContentField(value){const field=text(value,40).toLowerCase();return CONTENT_FIELDS.has(field)?field:""}
function contentValue(body,field){const limit=field==="html"?100000:field==="style"?20000:10000;return String(body?.value??"").slice(0,limit)}
async function adminPageContent(request,env){const unauthorized=requireAdmin(request,env);if(unauthorized)return unauthorized;const url=new URL(request.url);const page=normalizeContentPage(url.searchParams.get("page"));if(!page)return json({ok:false,message:"Đường dẫn trang không hợp lệ."},400);const result=await env.DB.prepare(`SELECT id,page,selector,field,value,created_at,updated_at FROM page_content_v40 WHERE page=? ORDER BY updated_at DESC,id DESC`).bind(page).all();return json({ok:true,page,changes:result.results||[]})}
async function savePageContent(request,env){const unauthorized=requireAdmin(request,env);if(unauthorized)return unauthorized;let body;try{body=await readJson(request)}catch(e){return json({ok:false,message:e.message||"Dữ liệu không hợp lệ."},400)}const page=normalizeContentPage(body.page),selector=text(body.selector,800),field=normalizeContentField(body.field),value=contentValue(body,field);if(!page)return json({ok:false,message:"Đường dẫn trang không hợp lệ."},400);if(!selector||selector.length<2)return json({ok:false,message:"Bộ chọn phần tử không hợp lệ."},400);if(!field)return json({ok:false,message:"Loại nội dung không hợp lệ."},400);const now=new Date().toISOString();const existing=await env.DB.prepare(`SELECT id,value FROM page_content_v40 WHERE page=? AND selector=? AND field=? LIMIT 1`).bind(page,selector,field).first();const id=existing?.id||`tb-content-${crypto.randomUUID()}`;if(existing){await env.DB.batch([env.DB.prepare(`INSERT INTO page_content_history_v40 (id,content_id,page,selector,field,value,changed_at) VALUES (?,?,?,?,?,?,?)`).bind(`tb-history-${crypto.randomUUID()}`,id,page,selector,field,String(existing.value??""),now),env.DB.prepare(`UPDATE page_content_v40 SET value=?,updated_at=? WHERE id=?`).bind(value,now,id)])}else{await env.DB.prepare(`INSERT INTO page_content_v40 (id,page,selector,field,value,created_at,updated_at) VALUES (?,?,?,?,?,?,?)`).bind(id,page,selector,field,value,now,now).run()}return json({ok:true,id,page,selector,field,value,updated_at:now,message:"Đã lưu nội dung lên Cloudflare D1."})}
async function deletePageContent(request,env){const unauthorized=requireAdmin(request,env);if(unauthorized)return unauthorized;let body;try{body=await readJson(request)}catch(e){return json({ok:false,message:e.message||"Dữ liệu không hợp lệ."},400)}const id=text(body.id,160),page=normalizeContentPage(body.page),selector=text(body.selector,800),field=normalizeContentField(body.field);let result;if(id)result=await env.DB.prepare("DELETE FROM page_content_v40 WHERE id=?").bind(id).run();else if(page&&selector&&field)result=await env.DB.prepare(`DELETE FROM page_content_v40 WHERE page=? AND selector=? AND field=?`).bind(page,selector,field).run();else return json({ok:false,message:"Thiếu thông tin thay đổi cần xóa."},400);if(!result.meta?.changes)return json({ok:false,message:"Không tìm thấy thay đổi cần xóa."},404);return json({ok:true,message:"Đã xóa thay đổi và khôi phục nội dung gốc."})}
async function resetPageContent(request,env){const unauthorized=requireAdmin(request,env);if(unauthorized)return unauthorized;let body;try{body=await readJson(request)}catch(e){return json({ok:false,message:e.message||"Dữ liệu không hợp lệ."},400)}const page=normalizeContentPage(body.page);if(!page)return json({ok:false,message:"Đường dẫn trang không hợp lệ."},400);if(body.confirm!=="RESET_PAGE")return json({ok:false,message:"Thiếu mã xác nhận đặt lại trang."},400);const result=await env.DB.prepare("DELETE FROM page_content_v40 WHERE page=?").bind(page).run();return json({ok:true,deleted:Number(result.meta?.changes||0),message:"Đã khôi phục toàn bộ nội dung gốc của trang."})}
export async function onRequest(context){const {request,env,params}=context;if(!env.DB)return json({ok:false,message:"Cloudflare D1 chưa được liên kết với Pages project."},503);const raw=Array.isArray(params.path)?params.path.join("/"):String(params.path||"");const path=`/${raw}`;const method=request.method.toUpperCase();try{if(path==="/content"&&method==="GET")return adminPageContent(request,env);if(path==="/save"&&method==="POST")return savePageContent(request,env);if(path==="/delete"&&method==="POST")return deletePageContent(request,env);if(path==="/reset-page"&&method==="POST")return resetPageContent(request,env);return json({ok:false,message:"Không tìm thấy API Studio."},404)}catch(error){return json({ok:false,message:"Lỗi máy chủ Studio.",detail:String(error?.message||error)},500)}}